version: '3'

volumes:
  mariadb_data:
      driver: local
  keycloak_data:
      driver: local

networks:
  network:
      driver: bridge

services:
  mariadb:
      image: mariadb:latest
      volumes:
        - mariadb_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: strong#password#2345
        MYSQL_DATABASE: keycloakDB
        MYSQL_USER: keycloakadmin
        MYSQL_PASSWORD: keycloak#2345
      ports:
        - 3306:3306
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
      networks:
        - network
  keycloak:
      image: jboss/keycloak:12.0.4
      volumes:
        - keycloak_data:/opt/jboss/keycloak/standalone/
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_USER: keycloakadmin
        DB_PASSWORD: keycloak#2345
        DB_DATABASE: keycloakDB
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin#2345
        PROXY_ADDRESS_FORWARDING: "true"
      ports:
        - 8080:8080
        - 8443:8443
        - 9990:9990
      command:
        - -b 0.0.0.0
        - -bmanagement 0.0.0.0
      restart: always
      healthcheck:
        test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/auth/realms/master"]
        interval: 30s
        timeout: 10s
        start_period: 5m
        retries: 10
      networks:
        - network
      depends_on:
        mariadb:
          condition: service_healthy

# Default application username and password.
# DB User: root, Password: strong#password#2345
# Kcloak DB User: keycloakadmin, Password: keycloak#2345, DB: keycloakDB
# Kcloak Login Admin User: admin, Password: admin#2345
